[2025-03-30T18:39:24.008+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-30T18:39:24.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_deliverable.query_hive_worst_air_quality manual__2025-03-30T18:38:06.870864+00:00 [queued]>
[2025-03-30T18:39:24.028+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_deliverable.query_hive_worst_air_quality manual__2025-03-30T18:38:06.870864+00:00 [queued]>
[2025-03-30T18:39:24.028+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-30T18:39:24.041+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): query_hive_worst_air_quality> on 2025-03-30 18:38:06.870864+00:00
[2025-03-30T18:39:24.047+0000] {standard_task_runner.py:64} INFO - Started process 238 to run task
[2025-03-30T18:39:24.050+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_deliverable', 'query_hive_worst_air_quality', 'manual__2025-03-30T18:38:06.870864+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/dag_deliverable.py', '--cfg-path', '/tmp/tmpu519ypou']
[2025-03-30T18:39:24.051+0000] {standard_task_runner.py:91} INFO - Job 187: Subtask query_hive_worst_air_quality
[2025-03-30T18:39:24.074+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_deliverable.query_hive_worst_air_quality manual__2025-03-30T18:38:06.870864+00:00 [running]> on host airflow
[2025-03-30T18:39:24.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_deliverable' AIRFLOW_CTX_TASK_ID='query_hive_worst_air_quality' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T18:38:06.870864+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T18:38:06.870864+00:00'
[2025-03-30T18:39:24.116+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-30T18:39:24.133+0000] {base.py:84} INFO - Using connection ID 'hive_default' for task execution.
[2025-03-30T18:39:24.154+0000] {hive.py:475} INFO - USE `default`
[2025-03-30T18:39:24.168+0000] {hive.py:475} INFO - SELECT
             record_timestamp,
             air_salon,
             air_chambre,
             air_bureau,
             air_exterieur,
             MAX(air_salon, air_chambre, air_bureau, air_exterieur) AS max_air_quality
             FROM weather.sensor_data
             ORDER BY max_air_quality DESC 
        
[2025-03-30T18:39:24.207+0000] {dag_deliverable.py:223} ERROR - ‚ùå Error al consultar Hive: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=40000, errorMessage='Error while compiling statement: FAILED: UDFArgumentTypeException Exactly one argument is expected.'), operationHandle=None)
[2025-03-30T18:39:24.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-30T18:39:24.208+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_deliverable.py", line 198, in query_hive_worst_air_quality
    cursor.execute(f"""SELECT
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=40000, errorMessage='Error while compiling statement: FAILED: UDFArgumentTypeException Exactly one argument is expected.'), operationHandle=None)
[2025-03-30T18:39:24.211+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_deliverable, task_id=query_hive_worst_air_quality, run_id=manual__2025-03-30T18:38:06.870864+00:00, execution_date=20250330T183806, start_date=20250330T183924, end_date=20250330T183924
[2025-03-30T18:39:24.222+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 187 for task query_hive_worst_air_quality (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=40000, errorMessage='Error while compiling statement: FAILED: UDFArgumentTypeException Exactly one argument is expected.'), operationHandle=None); 238)
[2025-03-30T18:39:24.261+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-30T18:39:24.273+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T18:39:24.280+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
