[2025-03-30T18:13:50.176+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-30T18:13:50.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_deliverable.query_hive_data manual__2025-03-30T18:13:31.656474+00:00 [queued]>
[2025-03-30T18:13:50.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_deliverable.query_hive_data manual__2025-03-30T18:13:31.656474+00:00 [queued]>
[2025-03-30T18:13:50.196+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-30T18:13:50.209+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): query_hive_data> on 2025-03-30 18:13:31.656474+00:00
[2025-03-30T18:13:50.216+0000] {standard_task_runner.py:64} INFO - Started process 202 to run task
[2025-03-30T18:13:50.218+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_deliverable', 'query_hive_data', 'manual__2025-03-30T18:13:31.656474+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/dag_deliverable.py', '--cfg-path', '/tmp/tmp4v4q8y5a']
[2025-03-30T18:13:50.219+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask query_hive_data
[2025-03-30T18:13:50.244+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_deliverable.query_hive_data manual__2025-03-30T18:13:31.656474+00:00 [running]> on host airflow
[2025-03-30T18:13:50.293+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_deliverable' AIRFLOW_CTX_TASK_ID='query_hive_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T18:13:31.656474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T18:13:31.656474+00:00'
[2025-03-30T18:13:50.293+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-30T18:13:50.307+0000] {base.py:84} INFO - Using connection ID 'hive_default' for task execution.
[2025-03-30T18:13:50.327+0000] {hive.py:475} INFO - USE `default`
[2025-03-30T18:13:50.344+0000] {hive.py:475} INFO - SELECT * FROM weather.sensor_data 
[2025-03-30T18:13:50.477+0000] {dag_deliverable.py:182} ERROR - ‚ùå Error al consultar Hive: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState=None, errorCode=1, errorMessage='Error while compiling statement: java.io.IOException: java.io.IOException: Not a file: hdfs://namenode:9000/topics/sensores/partition=0'), operationHandle=None)
[2025-03-30T18:13:50.477+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-30T18:13:50.478+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_deliverable.py", line 163, in query_hive
    cursor.execute(f"""SELECT * FROM {HIVE_TABLE} """)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState=None, errorCode=1, errorMessage='Error while compiling statement: java.io.IOException: java.io.IOException: Not a file: hdfs://namenode:9000/topics/sensores/partition=0'), operationHandle=None)
[2025-03-30T18:13:50.481+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_deliverable, task_id=query_hive_data, run_id=manual__2025-03-30T18:13:31.656474+00:00, execution_date=20250330T181331, start_date=20250330T181350, end_date=20250330T181350
[2025-03-30T18:13:50.493+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 174 for task query_hive_data (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState=None, errorCode=1, errorMessage='Error while compiling statement: java.io.IOException: java.io.IOException: Not a file: hdfs://namenode:9000/topics/sensores/partition=0'), operationHandle=None); 202)
[2025-03-30T18:13:50.510+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-30T18:13:50.519+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T18:13:50.519+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
